//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria_desktop.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libreriaEntities : DbContext
    {
        public libreriaEntities()
            : base("name=libreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<empleado> empleados { get; set; }
        public virtual DbSet<factura_productos> factura_productos { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<producto> productos { get; set; }
    }
}
