//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria_desktop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.factura_productos = new HashSet<factura_productos>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public long id_cliente { get; set; }
        public decimal total { get; set; }
        public int cant_prods { get; set; }
        public long id_empleado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_productos> factura_productos { get; set; }
    }
}
