//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria_desktop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_productos
    {
        public long id { get; set; }
        public long id_producto { get; set; }
        public int cant_prods { get; set; }
        public decimal sub_total { get; set; }
        public long id_factura { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
