//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libreria_desktop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.factura_productos = new HashSet<factura_productos>();
        }
    
        public long id { get; set; }
        public string producto1 { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public long id_categoria { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public byte activo { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_productos> factura_productos { get; set; }
    }
}
